language: ruby
rvm:
  - 1.9.3
  - 1.8.7
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
gemfile: Gemfile
env:
  - SUITE=cucumber
  - SUITE=spec
before_script:
  - export USE_BUNDLER=yes
  - rake db:drop
  - rake db:create
  - rake db:migrate
  - rake db:seed
  - rake db:test:prepare
script:
  - rake $SUITE
